services:
  mongodb:
    image: mongo:latest
    container_name: short-data
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - short-network

  backend:
    build:
      context: ./short-api
    container_name: short-api
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8081:8080" 
    env_file:
      - .env

    networks:
      - short-network

  frontend:
    build:
      context: ./short-ui
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: short-ui
    restart: unless-stopped
    
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - short-network

networks:
  short-network:
    driver: bridge

volumes:
  mongo_data: