services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - short-network

  backend:
    build:
      context: ./short-api
    container_name: short-api
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8081:8080" 
    environment:
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - MONGO_HOST=mongodb
      - APP_URL=http://your-domain.com
      - FRONT_URL=http://your-domain.com
      - URL_SUFFIX=u
    networks:
      - short-network

  frontend:
    build:
      context: ./short-ui
    container_name: short-ui
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - short-network

networks:
  short-network:
    driver: bridge

volumes:
  mongo_data: