app:
  url: ${APP_URL}
  front: ${FRONT_URL}
  url-suffix: ${URL_SUFFIX}
data:
  mongodb:
    host: ${MONGO_HOST}
    port: 27017
    database: ${MONGO_DATABASE}
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}