app:
  url: ${APP_URL}
  front: ${FRONT_URL}
  url-suffix: ${URL_SUFFIX}
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}