spring:
  application:
    name: url-shorter
  profiles:
    active: ${ACTIVE_PROFILE}
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXP}
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}