spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
#      host: mongodb
#      port: 27017
#      database: ${MONGO_DATABASE}
#      username: ${MONGO_USER}
#      password: ${MONGO_PASSWORD}
#      authentication-database: admin
  docker:
    compose:
      enabled: false
app:
  url: ${APP_URL}
  front: ${FRONT_URL}
  url-suffix: ${URL_SUFFIX}
